--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/vecnavium-pm-pl/SkyBlocksPM
build-by-default: true
branches:
- stable
projects:
  SkyBlocksPM:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.1.0
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
...
