--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/vecnavium-pm-pl/SkyBlocksPM
build-by-default: true
branches:
- stable
- pm5
projects:
  SkyBlocksPM:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
      - src: sylvrs/libMarshal/libMarshal
        version: ^1.4.3
        branch: "feature/virion"
...
